name: Sync to Gitee

on:
  push:
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actionhub/workflows/git-sync@v1
        name: Sync repo to gitee
        with:
          ssh-key: ${{ secrets.GITEE_TOKEN }}
          repo-url: git@gitee.com:cocos-creator-plugin/xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx.git
          force: true